### ISSUE TITLE
Can you provide the VIT/B 16 weights trained by CLIPself on the COCO dataset using Open AI clip?

### ISSUE THREAD

**Issue by winnerwu6** [wusize/CLIPSelf#2]
I want to use this weight, but my GPU is not enough for me to train it, I would be grateful if you could provide it！！！

**Comment by wusize** [comment]
Hi! Please find the weights under the [link](https://drive.google.com/file/d/15-CVC0mlKNPx09zslHnHGi7hYY9QKjJW/view?usp=sharing). But personally I suggest the use of EVA-CLIP models for higher performance and efficiency.

**Comment by winnerwu6** [comment]
Thank you for your reply, I appreciate it very much！
