### ISSUE TITLE
why class_weight  is uneven between categories in F-ViT？

### ISSUE THREAD

**Issue by 0xLDF** [wusize/CLIPSelf#23]
[link](https://github.com/wusize/CLIPSelf/blob/1c7fe9c5c38d800903d4754a89d7a8fcc7977101/F-ViT/configs/ov_coco/fvit_vitb16_upsample_fpn_bs64_3e_ovcoco_eva_original.py#L3)
```python
class_weight = [
    1.0, 1.0, 1.0, 1.0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 1.0, 1.0, 0, 0,
    1.0, 1.0, 1.0, 1.0, 0, 1.0, 0, 1.0, 1.0, 1.0, 0, 1.0, 0, 1.0, 1.0, 0, 1.0,
    0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 1.0, 0, 1.0, 1.0,
    1.0, 1.0, 1.0, 1.0, 0, 1.0, 1.0, 1.0, 0, 1.0, 1.0, 1.0, 1.0, 0, 1.0, 0.6
]
```
why class_weight  is uneven between categories in `F-ViT/configs/ov_coco/fvit_vitb16_upsample_fpn_bs64_3e_ovcoco_eva_original.py`？

**Comment by wusize** [comment]
The zero-value weights are for novel categories. Ideally, these categories should not appear in the training stage. However, to unify the model configs for training and testing, we set zero-value weights for the novel classes as a workaround.

**Comment by wendy26zhang** [comment]
Is the last number the background category? Why is the weight set to 0.6？
