### ISSUE TITLE
Google Drive links have expired

### ISSUE THREAD

**Issue by xiaomoguhz** [wusize/CLIPSelf#29]
Hello size@wusize , 

Thank you for your contributions in the field of open vocabulary dense prediction. However, I noticed that all the Google Drive links in the code are no longer working. Could you please re-upload the JSON files and weights? I would greatly appreciate it.

Thank you!
![image](https://github.com/user-attachments/assets/b6e46329-1b3e-47a3-82d9-5fd185d92621)

**Comment by wusize** [comment]
Hi! I noticed the issue. It seems to be because my university Google account has expired. I'll go to find why as all my checkpoints are on google drive.

**Comment by zhangyupeng123** [comment]
I also encountered this issue, have you found the cause and resolved it?

**Comment by wusize** [comment]
Hi, all! I temporarily resumed my Google account. It will be deleted again and the files will be moved to one drive in the coming days.

**Comment by xiaomoguhz** [comment]
Okay, thank you for your work. I have successfully obtained the weight file and JSON file from your Google Cloud Drive.  Close this issue
