### ISSUE TITLE
Request for Window Attention Weights and Code as Referenced in Table 7

### ISSUE THREAD

**Issue by cilinyan** [wusize/CLIPSelf#7]
Dear Authors,

I've been closely examining the details presented in Table 7 of your paper, where you compare the performance of Global Attention and Window Attention mechanisms. It appears that the main branch primarily provides the weights and code for the Global Attention version. I'm particularly interested in exploring the Window Attention variant further.

Would it be possible for you to share the weights and code specific to the Window Attention implementation mentioned in Table 7? 

Thank you very much for your assistance and for the invaluable contributions your work provides to the field.

Best regards.

**Comment by cilinyan** [comment]
I noticed that the authors seem to have provided the code for the Window Attention version in the window_attn branch. However, it appears that a checkpoint has not been provided. I hope the authors could share this part as well. Thank you very much!

**Comment by wusize** [comment]
Hi, I idiotically deleted the checkpoints when I was clearing my disk space. I will reproduce and then update them to you. You can also reproduce them by directly running the [scripts](https://github.com/wusize/CLIPSelf/tree/window_attn/scripts) ended with 'window_attention'.

**Comment by cilinyan** [comment]
thank you for your response!
