### ISSUE TITLE
Generating text embedding files

### ISSUE THREAD

**Issue by yhosoya66** [wusize/CLIPSelf#8]
Hi, thank you for your excellent work and the well-organized code you've shared. I really appreciate it!

I'd like to ask a few questions, if that's okay.

I'm interested in fine-tuning F-ViT from CLIPSelf (available in this repository) on a different dataset. For this purpose, we need to create embedding files like '[datasets/embeddings/coco_with_background_evaclip_vitb_16.pt](https://github.com/wusize/CLIPSelf/tree/main/F-ViT/datasets/embeddings)', which are essentially text embeddings for the target dataset, right?

Here are my questions:

1. How can I create these embedding files for my own dataset? Could you provide some guidance or a script to make text embedding files for arbitrary dataset?
2. Is the same text encoder consistently used across all configuration settings? If so, could you tell me which model you used?

Thanks for your help.

**Comment by wusize** [comment]
Hi, please use this [script](https://github.com/wusize/CLIPSelf/tree/main/F-ViT/tools) to generate text embeddings. Make sure using the corresponding text encoder to the ViT model.

**Comment by yhosoya66** [comment]
Thank you for your prompt reply, It works when I set the argument '--cache_dir' as the target pre-trained weight.
